from __future__ import annotations

from typing import Any

from . import schemas, tools


def register(ctx: Any) -> None:
    ctx.register_tool(
        name="merge_excel_sheets",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.MERGE_EXCEL_SHEETS_SCHEMA,
        handler=tools.merge_excel_sheets,
    )
    ctx.register_tool(
        name="export_excel_to_csv",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.EXPORT_EXCEL_TO_CSV_SCHEMA,
        handler=tools.export_excel_to_csv,
    )
    ctx.register_tool(
        name="convert_csv_to_excel",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.CONVERT_CSV_TO_EXCEL_SCHEMA,
        handler=tools.convert_csv_to_excel,
    )
    ctx.register_tool(
        name="filter_excel_rows",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.FILTER_EXCEL_ROWS_SCHEMA,
        handler=tools.filter_excel_rows,
    )
    ctx.register_tool(
        name="split_excel_file",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.SPLIT_EXCEL_FILE_SCHEMA,
        handler=tools.split_excel_file,
    )
    ctx.register_tool(
        name="deduplicate_excel_rows",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.DEDUPLICATE_EXCEL_ROWS_SCHEMA,
        handler=tools.deduplicate_excel_rows,
    )
    ctx.register_tool(
        name="aggregate_excel_rows",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.AGGREGATE_EXCEL_ROWS_SCHEMA,
        handler=tools.aggregate_excel_rows,
    )
    ctx.register_tool(
        name="validate_excel_file",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.VALIDATE_EXCEL_FILE_SCHEMA,
        handler=tools.validate_excel_file,
    )
    ctx.register_tool(
        name="select_excel_columns",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.SELECT_EXCEL_COLUMNS_SCHEMA,
        handler=tools.select_excel_columns,
    )
    ctx.register_tool(
        name="merge_excel_tables",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.MERGE_EXCEL_TABLES_SCHEMA,
        handler=tools.merge_excel_tables,
    )
    ctx.register_tool(
        name="vlookup_excel_tables",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.VLOOKUP_EXCEL_TABLES_SCHEMA,
        handler=tools.vlookup_excel_tables,
    )
    ctx.register_tool(
        name="transpose_excel_table",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.TRANSPOSE_EXCEL_TABLE_SCHEMA,
        handler=tools.transpose_excel_table,
    )
    ctx.register_tool(
        name="fill_excel_template",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.FILL_EXCEL_TEMPLATE_SCHEMA,
        handler=tools.fill_excel_template,
    )
    ctx.register_tool(
        name="rename_excel_sheets",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.RENAME_EXCEL_SHEETS_SCHEMA,
        handler=tools.rename_excel_sheets,
    )
    ctx.register_tool(
        name="format_excel_conditional",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.FORMAT_EXCEL_CONDITIONAL_SCHEMA,
        handler=tools.format_excel_conditional,
    )
    ctx.register_tool(
        name="format_excel_columns_as_text",
        toolset=schemas.TOOLSET_NAME,
        schema=schemas.FORMAT_EXCEL_COLUMNS_AS_TEXT_SCHEMA,
        handler=tools.format_excel_columns_as_text,
    )
